name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: BUILD

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s) \
        --build-arg SECRET_KEY="${{ vars.SECRET_KEY }}" \
        --build-arg DEBUG="${{ vars.DEBUG }}" \
        --build-arg ALLOWED_HOSTS="${{ vars.ALLOWED_HOSTS }}" \
        --build-arg OPENSEARCH_HOST="${{ vars.OPENSEARCH_HOST }}" \
        --build-arg OPENSEARCH_PORT="${{ vars.OPENSEARCH_PORT }}" \
        --build-arg OPENSEARCH_USER="${{ vars.OPENSEARCH_USER }}" \
        --build-arg OPENSEARCH_PASSWORD="${{ vars.OPENSEARCH_PASSWORD }}" \
        --build-arg OPENSEARCH_USE_SSL="${{ vars.OPENSEARCH_USE_SSL }}" \
        --build-arg OPENSEARCH_SSL_VERIFY="${{ vars.OPENSEARCH_SSL_VERIFY }}" \
        --build-arg CAMERA_HOST="${{ vars.CAMERA_HOST }}" \
        --build-arg CAMERA_PORT="${{ vars.CAMERA_PORT }}"
        
